### ISSUE TITLE
Contact email incorrect

### ISSUE THREAD

**Issue by PavelKvicera** [oracle/hospitality-api-docs#31]
Hi,
I am not sure if this belongs into repo issues but email address hospitality_apis_ww_group@oracle.com bounces back as non existent.

Pavel

**Comment by jneate** [comment]
> Hi, I am not sure if this belongs into repo issues but email address [hospitality_apis_ww_group@oracle.com](mailto:hospitality_apis_ww_group@oracle.com) bounces back as non existent.
> 
> Pavel

Thanks for spotting this!

The fix will be deployed shortly, if you need the email address before then, its `hospitality_apis_ww_grp@oracle.com`
