### ISSUE TITLE
[question] POS (Point of Sale) send sales

### ISSUE THREAD

**Issue by williamgueiros** [oracle/hospitality-api-docs#54]
Hi,

I am trying to send item to the Reservation.

example:  

- bottle of water, $ 1.00.

In pontman I found the colection 

- "Property Interfaces - Post Simple Charges"

-  - Post a billing charge including amount

That is a correct endpoint, to send data from POS to Oracle | Hospitality ? 

![Captura de tela 2023-05-06 135047](https://user-images.githubusercontent.com/19972/236636960-1a87cace-dc8d-495d-8be6-6a9498c63cfb.png)

**Comment by rb80** [comment]
Hi @williamgueiros, thank you for your interest in our APIs!
The answer to your question is yes, that is the right API operation for a POS to post charges.
If you're an integration partner we recommend posting this and similar "how to" questions on our dedicated Slack community.
