### ISSUE TITLE
The Postman Collection file `oracle-hospitality-property-workflows.postman_collection.json` is not valid JSON 

### ISSUE THREAD

**Issue by wernerm** [oracle/hospitality-api-docs#59]
The Postman Collection file, `oracle-hospitality-property-workflows.postman_collection.json`, is not valid JSON.

It cannot be parsed by JavaScript's JSON.parse() method.

**Comment by rb80** [comment]
Thank you for submitting this, @wernerm!  We're on it.

**Comment by rb80** [comment]
Fixed by #61
