### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by khaleghzade71** [oracle/hospitality-api-docs#70]
Hi , I am trying to use your APIs and test them ,
I have added the environment variables , but all of them are empty string ,  how can I use and test the APIs?

**Comment by rb80** [comment]
Hi @khaleghzade71 , we recommend starting [here](https://docs.oracle.com/en/industries/hospitality/integration-platform/ohipu/c_gs.htm#GettingStartedWithIntegrationPlatfo-7FAAA0AF), then once you've completed the Getting Started you can use [this guide](https://docs.oracle.com/en/industries/hospitality/integration-platform/ohipu/c_oracle_hospitality_property_apis.htm#CallingOracleHospitalityPropertyAPI-1BD5C2AF) (see table 6-4) for how to fill in the values.
